# Generated by Django 4.2.23 on 2025-08-07 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginlog',
            name='ip_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
