# Generated by Django 5.2.2 on 2025-08-07 17:59

import app.utils
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='aadhar_hash',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='bank_account_hash',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='pan_hash',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='uan_hash',
        ),
        migrations.AlterField(
            model_name='employee',
            name='aadhar_number',
            field=app.utils.EncryptedCharField(blank=True, max_length=12, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='pan_number',
            field=app.utils.EncryptedCharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='pf_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(regex='^\\+?\\d{10,15}$')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='uan_number',
            field=app.utils.EncryptedCharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
