# Generated by Django 4.2.23 on 2025-08-07 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_loginlog_ip_hash'),
        ('app', '0002_remove_employee_aadhar_hash_and_more'),
    ]

    operations = [
    ]
