# Generated by Django 5.2.2 on 2025-08-08 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_merge_20250807_2341'),
        ('app', '0003_resignationrequest'),
    ]

    operations = [
    ]
