# Generated by Django 5.2.2 on 2025-08-08 07:17

import app.utils
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_merge_20250807_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='aadhar_number',
            field=app.utils.EncryptedCharField(blank=True, max_length=12, null=True, unique=True, verbose_name='Aadhar Number'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='bank_account_number',
            field=app.utils.EncryptedCharField(blank=True, max_length=20, null=True, verbose_name='Bank Account Number'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='pan_number',
            field=app.utils.EncryptedCharField(max_length=20, unique=True, verbose_name='PAN Number'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='uan_number',
            field=app.utils.EncryptedCharField(max_length=20, unique=True, verbose_name='UAN Number'),
        ),
    ]
