# Generated by Django 5.2.2 on 2025-08-08 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_resignationrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resignationrequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='resignationrequest',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
