# Generated by Django 5.2.2 on 2025-08-08 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_resignationrequest_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resignationrequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='submitted', max_length=20),
        ),
        migrations.AlterField(
            model_name='resignationrequest',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-08-08 05:35:00'),
            preserve_default=False,
        ),
    ]
