# Generated by Django 5.2.2 on 2025-08-08 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_employee_cover_picture_employee_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='cover_picture',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='profile_picture',
        ),
    ]
