# Generated by Django 5.2.2 on 2025-08-08 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_merge_20250808_1226'),
        ('app', '0006_remove_employee_cover_picture_and_more'),
    ]

    operations = [
    ]
