# Generated by Django 5.2.2 on 2025-08-10 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_resignationrequest_status_and_more'),
        ('app', '0007_merge_20250808_1519'),
    ]

    operations = [
    ]
