# Generated by Django 4.2.23 on 2025-08-10 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_merge_20250808_1809'),
        ('app', '0009_alter_resignationrequest_status'),
    ]

    operations = [
    ]
