# Generated by Django 5.2.2 on 2025-08-11 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_skillcategory_careerresource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resignationrequest',
            name='signature_data',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
    ]
