# Generated by Django 5.2.2 on 2025-08-11 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_resignationrequest_signature_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resignationrequest',
            name='signature_data',
            field=models.TextField(blank=True, help_text='Base64 image of signature', null=True),
        ),
    ]
