# Generated by Django 5.2.2 on 2025-08-18 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_customuser_failed_attempts_customuser_is_locked_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='failed_attempts',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_locked',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='lock_time',
        ),
        migrations.DeleteModel(
            name='UnlockRequest',
        ),
    ]
