# Generated by Django 4.2.23 on 2025-08-19 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_customuser_failed_attempts_customuser_locked_until_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='lock_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
