# Generated by Django 5.2.2 on 2025-08-21 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_rename_name_employee_first_name_employee_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_check',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
    ]
