# Generated by Django 4.2.23 on 2025-08-19 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_customuser_is_locked_customuser_lock_expires_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unlockrequest',
            old_name='created_at',
            new_name='requested_at',
        ),
    ]
