# Generated by Django 4.2.23 on 2025-08-19 08:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_rename_created_at_unlockrequest_requested_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='unlockrequest',
            name='hr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_unlock_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
