# Generated by Django 4.2.23 on 2025-08-23 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_unlockrequest_hr'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
