# Generated by Django 4.2.23 on 2025-08-23 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_customuser_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='reason',
        ),
        migrations.AddField(
            model_name='unlockrequest',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
