# Generated by Django 5.2.2 on 2025-08-23 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_company_check_logo'),
        ('app', '0022_remove_customuser_reason_unlockrequest_reason'),
    ]

    operations = [
    ]
