# Generated by Django 4.2.23 on 2025-09-04 06:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_message_calllog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calllog',
            name='callee',
            field=models.ForeignKey(db_column='callee_id', on_delete=django.db.models.deletion.CASCADE, related_name='calls_received', to=settings.AUTH_USER_MODEL, to_field='employee_id'),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='caller',
            field=models.ForeignKey(db_column='caller_id', on_delete=django.db.models.deletion.CASCADE, related_name='calls_made', to=settings.AUTH_USER_MODEL, to_field='employee_id'),
        ),
        migrations.AlterField(
            model_name='message',
            name='receiver',
            field=models.ForeignKey(db_column='receiver_id', on_delete=django.db.models.deletion.CASCADE, related_name='recv_msgs', to=settings.AUTH_USER_MODEL, to_field='employee_id'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(db_column='sender_id', on_delete=django.db.models.deletion.CASCADE, related_name='sent_msgs', to=settings.AUTH_USER_MODEL, to_field='employee_id'),
        ),
    ]
