# Generated by Django 4.2.23 on 2025-09-04 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_calllog_callee_alter_calllog_caller_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='employee_id',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True),
        ),
    ]
