# Generated by Django 4.2.23 on 2025-09-15 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_call_rename_created_at_message_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='call',
            options={'ordering': ['-started_at']},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['timestamp']},
        ),
        migrations.AlterField(
            model_name='call',
            name='status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('ended', 'Ended'), ('missed', 'Missed')], default='ongoing', max_length=20),
        ),
    ]
