# Generated by Django 4.2.23 on 2025-09-16 06:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_alter_message_receiver_alter_message_sender'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_message', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('other_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recent_chats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
